// Svelte/svelte-app/src/App.svelte
<script>
	// Importy funkcí z balíčku Svelte a komponenty Task
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import Task from './Task.svelte';
  
	// Vytvoření reaktivní proměnné pro seznam úkolů a inicializace prázdným polem
	let tasks = writable([]);
	// Proměnná pro ukládání názvu nového úkolu z formuláře
	let newTaskTitle = '';
  // Funkce pro přidání nového úkolu do seznamu úkolů
	function addTask() {
		// Kontrola, zda je název nového úkolu neprázdný
	  if (newTaskTitle.trim()) {
		// Aktualizace seznamu úkolů - přidání nového úkolu
		tasks.update(arr => [...arr, { title: newTaskTitle, completed: false }]);
		// Vyprázdnění pole pro nový název úkolu
		newTaskTitle = '';
	  }
	}
  // Funkce pro odstranění úkolu ze seznamu na základě indexu
	function deleteTask(index) {
		// Aktualizace seznamu úkolů - odstranění úkolu s odpovídajícím indexem
	  tasks.update(arr => arr.filter((_, i) => i !== index));
	}
  // Funkce pro označení úkolu jako dokončeného nebo nedokončeného na základě indexu
	function completeTask(index) {
		// Aktualizace stavu úkolu - změna hodnoty 
	  tasks.update(arr => {
		arr[index].completed = !arr[index].completed;
		return arr;
	  });
	}
  </script>
  
  <style>
	/* Styly pro hlavní kontejner aplikace */
	.app-container {
	  max-width: 600px;
	  margin: 0 auto;
	  padding: 20px;
	  border: 1px solid #ddd;
	  border-radius: 10px;
	  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
	}
	/* Styly pro nadpis */
	h1 {
	  text-align: center;
	  margin-bottom: 20px;
	  font-size: 24px;
	  color: #333;
	}
  /* Styly pro vstupní pole */
	input[type="text"] {
	  width: calc(100% - 80px);
	  padding: 10px;
	  font-size: 16px;
	  border: 1px solid #ddd;
	  border-radius: 5px;
	  margin-bottom: 10px;
	}
  /* Styly pro tlačítka */
	button {
	  padding: 10px 20px;
	  font-size: 16px;
	  background-color: #007bff;
	  color: #fff;
	  border: none;
	  border-radius: 5px;
	  cursor: pointer;
	}
  
	button:hover {
	  background-color: #0056b3;
	}
  </style>
  
  <div class="app-container">
	<!-- Hlavní nadpis aplikace -->
	<h1>Seznam úkolů</h1>
	<!-- Formulář pro přidání nového úkolu -->
	<div style="display: flex; margin-bottom: 20px;">
	  <input type="text" bind:value={newTaskTitle} placeholder="Přidat nový úkol">
	  <button on:click={addTask}>Přidat úkol</button>
	</div>
  <!-- Seznam úkolů s použitím komponenty Task -->
	{#each $tasks as task, index}
	  <Task {task} onDelete={() => deleteTask(index)} onComplete={() => completeTask(index)} />
	{/each}
  </div>

// Vue/todo-app/src/App.vue
<template>
  <div id="app" class="app-container">
    <div class="todo-container">
      <h1 class="app-title">Seznam úkolů!</h1>
      <div class="todo-form">
        <input v-model="newTask" @keyup.enter="addTask" placeholder="Přidat nový úkol" class="task-input">
        <button @click="addTask" class="add-button">Přidat úkol</button>
      </div>
      <ul class="todo-list">
        <li v-for="(task, index) in tasks" :key="index" class="todo-item">
          <input type="checkbox" v-model="task.completed" class="task-checkbox">
          <span :class="{ completed: task.completed }" class="task-text">{{ task.text }}</span>
          <button @click="deleteTask(index)" class="delete-button">X</button>
        </li>
      </ul>
    </div>
  </div>c
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      newTask: '',
      tasks: []
    };
  },
  methods: {
    addTask() {
      if (this.newTask.trim() !== '') {
        this.tasks.push({ text: this.newTask, completed: false });
        this.newTask = '';
      }
    },
    deleteTask(index) {
      this.tasks.splice(index, 1);
    }
  }
}
</script>

<style scoped>
.app-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #f5f5f5;
}

.todo-container {
  width: 400px;
  padding: 20px;
  border-radius: 10px;
  background-color: white;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.app-title {
  margin-bottom: 20px;
  text-align: center;
  color: #333;
}

.todo-form {
  display: flex;
  margin-bottom: 20px;
}

.task-input {
  flex: 1;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px 0 0 5px;
}

.add-button {
  padding: 10px 20px;
  background-color: #007bff;
  border: none;
  border-radius: 0 5px 5px 0;
  color: white;
  cursor: pointer;
}

.todo-list {
  list-style: none;
  padding: 0;
}

.todo-item {
  display: flex;
  align-items: center;
  border-bottom: 1px solid #eee;
  padding: 10px 0;
}

.task-checkbox {
  margin-right: 10px;
}

.task-text {
  flex: 1;
  color: #333;
}

.completed {
  text-decoration: line-through;
}

.delete-button {
  padding: 5px;
  background-color: #dc3545;
  border: none;
  border-radius: 50%;
  color: white;
  cursor: pointer;
}
</style>
